version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8080:80
    container_name: nginx
    depends_on:
      - app
    networks:
      - app-network
    # links:
    #   - app
    #   - node

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: app
    networks:
      - app-network 
    environment:
      - DB_HOST=db
      # - MAIL_HOST=mailpit
    # links:
    #   - db
    #   - node

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: online_store_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: db
    networks:
      - app-network

  # node:
  #   image: node:18-alpine
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./:/var/www
  #   working_dir: /var/www
  #   tty: true

  # mailpit:
  #   image: axllent/mailpit
  #   container_name: mailpit
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025" 
  #   networks:
  #     - app-network
    
networks:
  app-network:
    driver: bridge